// <auto-generated />
namespace Schedule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ReferncesStateCase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReferncesStateCase));
        
        string IMigrationMetadata.Id
        {
            get { return "202309261431198_ReferncesStateCase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
